# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equalizer_layout.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(944, 447)
        self.slider_25 = QtWidgets.QSlider(Form)
        self.slider_25.setGeometry(QtCore.QRect(100, 170, 22, 160))
        self.slider_25.setMinimum(-12)
        self.slider_25.setMaximum(12)
        self.slider_25.setOrientation(QtCore.Qt.Vertical)
        self.slider_25.setObjectName("slider_25")
        self.slider_40 = QtWidgets.QSlider(Form)
        self.slider_40.setGeometry(QtCore.QRect(160, 170, 22, 160))
        self.slider_40.setMinimum(-12)
        self.slider_40.setMaximum(12)
        self.slider_40.setOrientation(QtCore.Qt.Vertical)
        self.slider_40.setObjectName("slider_40")
        self.slider_63 = QtWidgets.QSlider(Form)
        self.slider_63.setGeometry(QtCore.QRect(210, 170, 22, 160))
        self.slider_63.setMinimum(-12)
        self.slider_63.setMaximum(12)
        self.slider_63.setOrientation(QtCore.Qt.Vertical)
        self.slider_63.setObjectName("slider_63")
        self.slider_100 = QtWidgets.QSlider(Form)
        self.slider_100.setGeometry(QtCore.QRect(260, 170, 22, 160))
        self.slider_100.setMinimum(-12)
        self.slider_100.setMaximum(12)
        self.slider_100.setOrientation(QtCore.Qt.Vertical)
        self.slider_100.setObjectName("slider_100")
        self.slider_160 = QtWidgets.QSlider(Form)
        self.slider_160.setGeometry(QtCore.QRect(310, 170, 22, 160))
        self.slider_160.setMinimum(-12)
        self.slider_160.setMaximum(12)
        self.slider_160.setOrientation(QtCore.Qt.Vertical)
        self.slider_160.setObjectName("slider_160")
        self.slider_630 = QtWidgets.QSlider(Form)
        self.slider_630.setGeometry(QtCore.QRect(460, 170, 22, 160))
        self.slider_630.setMinimum(-12)
        self.slider_630.setMaximum(12)
        self.slider_630.setOrientation(QtCore.Qt.Vertical)
        self.slider_630.setObjectName("slider_630")
        self.slider_250 = QtWidgets.QSlider(Form)
        self.slider_250.setGeometry(QtCore.QRect(360, 170, 22, 160))
        self.slider_250.setMinimum(-12)
        self.slider_250.setMaximum(12)
        self.slider_250.setOrientation(QtCore.Qt.Vertical)
        self.slider_250.setObjectName("slider_250")
        self.slider_400 = QtWidgets.QSlider(Form)
        self.slider_400.setGeometry(QtCore.QRect(410, 170, 22, 160))
        self.slider_400.setMinimum(-12)
        self.slider_400.setMaximum(12)
        self.slider_400.setOrientation(QtCore.Qt.Vertical)
        self.slider_400.setObjectName("slider_400")
        self.slider_1k = QtWidgets.QSlider(Form)
        self.slider_1k.setGeometry(QtCore.QRect(510, 170, 22, 160))
        self.slider_1k.setMinimum(-12)
        self.slider_1k.setMaximum(12)
        self.slider_1k.setOrientation(QtCore.Qt.Vertical)
        self.slider_1k.setObjectName("slider_1k")
        self.slider_4k = QtWidgets.QSlider(Form)
        self.slider_4k.setGeometry(QtCore.QRect(660, 170, 22, 160))
        self.slider_4k.setMinimum(-12)
        self.slider_4k.setMaximum(12)
        self.slider_4k.setOrientation(QtCore.Qt.Vertical)
        self.slider_4k.setObjectName("slider_4k")
        self.slider_1k6 = QtWidgets.QSlider(Form)
        self.slider_1k6.setGeometry(QtCore.QRect(560, 170, 22, 160))
        self.slider_1k6.setMinimum(-12)
        self.slider_1k6.setMaximum(12)
        self.slider_1k6.setOrientation(QtCore.Qt.Vertical)
        self.slider_1k6.setObjectName("slider_1k6")
        self.slider_2k5 = QtWidgets.QSlider(Form)
        self.slider_2k5.setGeometry(QtCore.QRect(610, 170, 22, 160))
        self.slider_2k5.setMinimum(-12)
        self.slider_2k5.setMaximum(12)
        self.slider_2k5.setOrientation(QtCore.Qt.Vertical)
        self.slider_2k5.setObjectName("slider_2k5")
        self.slider_6k3 = QtWidgets.QSlider(Form)
        self.slider_6k3.setGeometry(QtCore.QRect(710, 170, 22, 160))
        self.slider_6k3.setMinimum(-12)
        self.slider_6k3.setMaximum(12)
        self.slider_6k3.setOrientation(QtCore.Qt.Vertical)
        self.slider_6k3.setObjectName("slider_6k3")
        self.slider_10k = QtWidgets.QSlider(Form)
        self.slider_10k.setGeometry(QtCore.QRect(760, 170, 22, 160))
        self.slider_10k.setMinimum(-12)
        self.slider_10k.setMaximum(12)
        self.slider_10k.setOrientation(QtCore.Qt.Vertical)
        self.slider_10k.setObjectName("slider_10k")
        self.slider_16k = QtWidgets.QSlider(Form)
        self.slider_16k.setGeometry(QtCore.QRect(810, 170, 22, 160))
        self.slider_16k.setMinimum(-12)
        self.slider_16k.setMaximum(12)
        self.slider_16k.setOrientation(QtCore.Qt.Vertical)
        self.slider_16k.setObjectName("slider_16k")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 110, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 310, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.btn_filter = QtWidgets.QPushButton(Form)
        self.btn_filter.setGeometry(QtCore.QRect(220, 380, 151, 41))
        self.btn_filter.setObjectName("btn_filter")
        self.btn_save = QtWidgets.QPushButton(Form)
        self.btn_save.setGeometry(QtCore.QRect(390, 380, 151, 41))
        self.btn_save.setObjectName("btn_save")
        self.btn_reset = QtWidgets.QPushButton(Form)
        self.btn_reset.setGeometry(QtCore.QRect(560, 380, 151, 41))
        self.btn_reset.setObjectName("btn_reset")
        self.btn_choose = QtWidgets.QPushButton(Form)
        self.btn_choose.setGeometry(QtCore.QRect(100, 50, 151, 41))
        self.btn_choose.setObjectName("btn_choose")
        self.dropdown_presets = QtWidgets.QComboBox(Form)
        self.dropdown_presets.setGeometry(QtCore.QRect(650, 50, 201, 41))
        self.dropdown_presets.setObjectName("dropdown_presets")
        self.dropdown_presets.addItem("")
        self.dropdown_presets.addItem("")
        self.dropdown_presets.addItem("")
        self.dropdown_presets.addItem("")
        self.dropdown_presets.addItem("")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(720, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.text_filename = QtWidgets.QLineEdit(Form)
        self.text_filename.setGeometry(QtCore.QRect(280, 50, 341, 41))
        self.text_filename.setObjectName("text_filename")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(380, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(860, 230, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(860, 150, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(860, 310, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(100, 330, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(160, 330, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(210, 330, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(250, 330, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(510, 330, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(550, 330, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(660, 330, 21, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(700, 330, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(750, 330, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(800, 330, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(300, 330, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(350, 330, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(400, 330, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(450, 330, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(600, 330, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Засил."))
        self.label_3.setText(_translate("Form", "- 12 db"))
        self.label_4.setText(_translate("Form", "- 12 db"))
        self.label_5.setText(_translate("Form", "+ 12 db"))
        self.btn_filter.setText(_translate("Form", "Филтрирај"))
        self.btn_save.setText(_translate("Form", "Зачувај"))
        self.btn_reset.setText(_translate("Form", "Ресет"))
        self.btn_choose.setText(_translate("Form", "Избери"))
        self.dropdown_presets.setItemText(0, _translate("Form", "rock"))
        self.dropdown_presets.setItemText(1, _translate("Form", "jazz"))
        self.dropdown_presets.setItemText(2, _translate("Form", "blues"))
        self.dropdown_presets.setItemText(3, _translate("Form", "classical"))
        self.dropdown_presets.setItemText(4, _translate("Form", "pop"))
        self.label_2.setText(_translate("Form", "Presets"))
        self.label_6.setText(_translate("Form", "Име на Фајлот"))
        self.label_7.setText(_translate("Form", "- 12 db"))
        self.label_8.setText(_translate("Form", "+ 12 db"))
        self.label_9.setText(_translate("Form", "- 12 db"))
        self.label_10.setText(_translate("Form", "25"))
        self.label_11.setText(_translate("Form", "40"))
        self.label_12.setText(_translate("Form", "63"))
        self.label_14.setText(_translate("Form", " 100"))
        self.label_18.setText(_translate("Form", "1k"))
        self.label_19.setText(_translate("Form", " 1.6k"))
        self.label_21.setText(_translate("Form", "4k"))
        self.label_22.setText(_translate("Form", "6.3k"))
        self.label_23.setText(_translate("Form", " 10k"))
        self.label_24.setText(_translate("Form", " 16k"))
        self.label_25.setText(_translate("Form", " 160"))
        self.label_26.setText(_translate("Form", " 250"))
        self.label_27.setText(_translate("Form", " 400"))
        self.label_28.setText(_translate("Form", " 630"))
        self.label_20.setText(_translate("Form", " 2.5k"))
